/**
 * Offline Sync Endpoint
 * Processes queued mutations from offline clients
 * 
 * POST /api/sync/batch
 * Body: { mutations: [ { type, mutation, signature }, ... ] }
 */

import express from 'express';
import db from '../src/db/postgres.js';
import { authenticateToken } from '../src/shared/middleware/auth.js';
import {
  verifyMutationSignature,
  validateMutationStructure,
  isSupportedMutation,
  MUTATION_TYPES,
} from '../src/services/hmacVerifier.js';

const router = express.Router();

/**
 * POST /api/sync/batch
 * Sync queued offline mutations to the server
 * 
 * Rate limit: Checked by global middleware (3 req/sec)
 */
router.post('/batch', authenticateToken, async (req, res) => {
  const userId = req.user?.userId;
  const jwtIat = req.user?.iat;  // Issued-at timestamp from JWT
  
  if (!userId || !jwtIat) {
    return res.status(401).json({ 
      error: 'Unauthorized: Missing user context' 
    });
  }

  const { mutations = [] } = req.body;

  if (!Array.isArray(mutations)) {
    return res.status(400).json({ 
      error: 'Invalid request: mutations must be an array' 
    });
  }

  if (mutations.length === 0) {
    return res.status(400).json({ 
      error: 'No mutations to sync' 
    });
  }

  if (mutations.length > 100) {
    return res.status(400).json({ 
      error: 'Too many mutations in single batch (max 100)' 
    });
  }

  try {
    // Use transaction helper for proper connection management
    const results = await db.transaction(async (client) => {
      const batchResults = [];

      for (const mutation of mutations) {
        const result = await processMutation(
          client,
          userId,
          jwtIat,
          mutation
        );
        batchResults.push(result);
      }

      return batchResults;
    });

    console.log(`✅ Synced ${results.filter(r => r.success).length}/${results.length} mutations for user ${userId}`);

    res.json({
      success: true,
      synced: results.filter(r => r.success).length,
      failed: results.filter(r => !r.success).length,
      results,
    });
  } catch (error) {
    console.error('❌ Sync error:', error);
    res.status(500).json({ 
      error: 'Sync failed',
      message: error.message,
    });
  }
});

/**
 * Process a single mutation with full validation
 * @param {pg.Client} client - Database client (from transaction)
 * @param {number} userId - User ID
 * @param {number} jwtIat - JWT issued-at timestamp
 * @param {object} mutation - Mutation object { type, mutation, signature }
 * @returns {Promise<object>} Result { success, idempotencyKey, error? }
 */
async function processMutation(client, userId, jwtIat, mutation) {
  try {
    // 1. Validate structure
    const structureValidation = validateMutationStructure(mutation);
    if (!structureValidation.valid) {
      return {
        success: false,
        error: `Structure validation failed: ${structureValidation.errors.join(', ')}`,
      };
    }

    // 2. Check if mutation type is supported
    if (!isSupportedMutation(mutation.type)) {
      return {
        success: false,
        error: `Unsupported mutation type: ${mutation.type}`,
      };
    }

    // 3. Extract idempotency key (generated by client during mutation)
    const idempotencyKey = mutation.mutation.idempotencyKey;
    if (!idempotencyKey) {
      return {
        success: false,
        error: 'Missing idempotency key',
      };
    }

    // 4. HMAC verification (tamper detection)
    // signingIat is optional and may arrive as null/empty/invalid from legacy clients.
    // Only accept a positive integer iat; otherwise fallback to jwtIat.
    const candidateSigningIat = Number(mutation.signingIat);
    const hasValidSigningIat = Number.isInteger(candidateSigningIat) && candidateSigningIat > 0;

    // Try jwtIat first (most common), then optional client-provided signingIat.
    // This handles token refresh races while remaining backward compatible.
    const verificationIats = hasValidSigningIat && candidateSigningIat !== jwtIat
      ? [jwtIat, candidateSigningIat]
      : [jwtIat];

    const signatureValid = verificationIats.some((iat) => verifyMutationSignature(
      mutation.mutation,
      mutation.signature,
      userId,
      iat
    ));

    if (!signatureValid) {
      console.warn(
        `⚠️ HMAC verification failed for user ${userId}, mutation ${mutation.type}, triedIats=${verificationIats.join(',')}`
      );
      return {
        success: false,
        idempotencyKey,
        error: 'HMAC verification failed - mutation may be tampered',
        details: {
          triedIats: verificationIats,
          hasSigningIat: hasValidSigningIat,
        },
      };
    }

    // 5. Check idempotency - prevent duplicate processing
    const existingResult = await client.query(
      `SELECT response, status FROM idempotency_keys 
       WHERE user_id = $1 AND idempotency_key = $2`,
      [userId, idempotencyKey]
    );

    if (existingResult.rows.length > 0) {
      const existing = existingResult.rows[0];
      if (existing.status === 'completed') {
        console.log(`🔁 Duplicate mutation detected, replaying response for ${idempotencyKey}`);
        return {
          success: true,
          idempotencyKey,
          duplicate: true,
          response: existing.response,
        };
      }
    }

    // 6. Record attempt and process mutation
    const mutationData = mutation.mutation.data;
    let response = null;

    try {
      // TODO: Implement actual mutation handlers
      // For now, just record as completed
      
      switch (mutation.type) {
        case MUTATION_TYPES.ADD_TO_CART:
          response = await handleAddToCart(client, userId, mutationData);
          break;
        case MUTATION_TYPES.REMOVE_FROM_CART:
          response = await handleRemoveFromCart(client, userId, mutationData);
          break;
        case MUTATION_TYPES.UPDATE_QUANTITY:
          response = await handleUpdateQuantity(client, userId, mutationData);
          break;
        case MUTATION_TYPES.ADD_TO_WISHLIST:
          response = await handleAddToWishlist(client, userId, mutationData);
          break;
        case MUTATION_TYPES.REMOVE_FROM_WISHLIST:
          response = await handleRemoveFromWishlist(client, userId, mutationData);
          break;
        default:
          // Acknowledge mutation received but not processed yet
          response = { acknowledged: true };
      }

      // 7. Store successful result for idempotency replay
      await client.query(
        `INSERT INTO idempotency_keys (user_id, idempotency_key, mutation_type, payload, response, status)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (user_id, idempotency_key) 
         DO UPDATE SET response = $5, status = $6`,
        [
          userId,
          idempotencyKey,
          mutation.type,
          JSON.stringify(mutationData),
          JSON.stringify(response),
          'completed',
        ]
      );

      console.log(`✅ Mutation processed: ${mutation.type} for user ${userId}`);

      return {
        success: true,
        idempotencyKey,
        response,
      };
    } catch (error) {
      // 8. Store error for debugging
      await client.query(
        `INSERT INTO idempotency_keys (user_id, idempotency_key, mutation_type, payload, status, error_message)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (user_id, idempotency_key) 
         DO UPDATE SET status = $5, error_message = $6`,
        [
          userId,
          idempotencyKey,
          mutation.type,
          JSON.stringify(mutationData),
          'failed',
          error.message,
        ]
      );

      throw error;
    }
  } catch (error) {
    console.error('❌ Mutation processing error:', error);
    return {
      success: false,
      error: error.message,
    };
  }
}

/**
 * Placeholder mutation handlers
 * These should be implemented based on your business logic
 */

async function handleAddToCart(client, userId, data) {
  /**
   * Expected data: { productId, quantity, idempotencyKey }
   */
  const { productId, quantity } = data;
  
  if (!productId || !quantity) {
    throw new Error('Missing required fields: productId, quantity');
  }
  
  // For offline sync, cart operations are typically local-only
  // We just acknowledge receipt of the mutation
  // The actual cart is managed client-side in IndexedDB
  
  console.log(`📦 ADD_TO_CART: product ${productId} x${quantity} for user ${userId}`);
  
  return {
    success: true,
    message: 'Item added to cart (synced)',
    productId,
    quantity
  };
}

async function handleRemoveFromCart(client, userId, data) {
  /**
   * Expected data: { productId, idempotencyKey }
   */
  const { productId } = data;
  
  if (!productId) {
    throw new Error('Missing required field: productId');
  }
  
  console.log(`🗑️ REMOVE_FROM_CART: product ${productId} for user ${userId}`);
  
  return {
    success: true,
    message: 'Item removed from cart (synced)',
    productId
  };
}

async function handleUpdateQuantity(client, userId, data) {
  /**
   * Expected data: { productId, quantity, idempotencyKey }
   */
  const { productId, quantity } = data;
  
  if (!productId || quantity === undefined) {
    throw new Error('Missing required fields: productId, quantity');
  }
  
  if (quantity <= 0) {
    throw new Error('Quantity must be greater than 0');
  }
  
  console.log(`📊 UPDATE_QUANTITY: product ${productId} to quantity ${quantity} for user ${userId}`);
  
  return {
    success: true,
    message: 'Quantity updated (synced)',
    productId,
    quantity
  };
}

async function handleAddToWishlist(client, userId, data) {
  /**
   * Expected data: { productId, idempotencyKey }
   */
  const { productId } = data;
  
  if (!productId) {
    throw new Error('Missing required field: productId');
  }
  
  // Check if product exists
  const productResult = await client.query(
    'SELECT id FROM products WHERE id = $1',
    [productId]
  );
  
  if (productResult.rows.length === 0) {
    throw new Error(`Product ${productId} not found`);
  }
  
  // Add to favorites (or update if exists)
  const result = await client.query(
    `INSERT INTO favorites (user_id, product_id)
     VALUES ($1, $2)
     ON CONFLICT (user_id, product_id) 
     DO NOTHING
     RETURNING id`,
    [userId, productId]
  );
  
  console.log(`❤️ ADD_TO_WISHLIST: product ${productId} for user ${userId}`);
  
  return {
    success: true,
    message: 'Item added to wishlist (synced)',
    productId,
    created: result.rows.length > 0
  };
}

async function handleRemoveFromWishlist(client, userId, data) {
  /**
   * Expected data: { productId, idempotencyKey }
   */
  const { productId } = data;
  
  if (!productId) {
    throw new Error('Missing required field: productId');
  }
  
  // Remove from favorites
  const result = await client.query(
    'DELETE FROM favorites WHERE user_id = $1 AND product_id = $2',
    [userId, productId]
  );
  
  console.log(`💔 REMOVE_FROM_WISHLIST: product ${productId} for user ${userId}`);
  
  return {
    success: true,
    message: 'Item removed from wishlist (synced)',
    productId,
    deleted: result.rowCount > 0
  };
}

export default router;
