import React from 'react';
import { useTranslation } from 'react-i18next';
import { printSingleBarcode } from '../lib/barcodePrinting.js';

/**
 * Post-Creation Barcode Modal
 * Shows immediately after product is created
 * Allows user to copy/print barcode before continuing
 */
export const PostCreationBarcodeModal = ({ product, onClose, onViewProduct }) => {
  const { t } = useTranslation();
  const [copying, setCopying] = React.useState(false);
  const [printing, setPrinting] = React.useState(false);

  const handleCopy = async () => {
    if (!product?.barcode) return;
    setCopying(true);
    try {
      await navigator.clipboard.writeText(product.barcode);
      setTimeout(() => setCopying(false), 1500);
    } catch (err) {
      console.error('Failed to copy:', err);
      setCopying(false);
    }
  };

  const handlePrint = async () => {
    if (!product?.barcode) return;
    setPrinting(true);
    try {
      await printSingleBarcode({
        barcode: product.barcode,
        price: product.selling_price,
        productName: product.product_name || product.name || product.sku,
        width: '250px',
        height: '180px'
      });
    } catch (err) {
      console.error('Failed to print:', err);
    } finally {
      setPrinting(false);
    }
  };

  return (
    <div className="barcode-modal-overlay">
      <div className="barcode-modal-content">
        {/* Header */}
        <div className="modal-header">
          <div>
            <h2>✓ {t('barcode.productCreated')}</h2>
            <p>{t('barcode.autoGenerated')}</p>
          </div>
          <button type="button" onClick={onClose} className="modal-close">
            ×
          </button>
        </div>

        {/* Barcode Display */}
        <div className="modal-body">
          {/* Product Info */}
          <div className="product-info">
            <div className="info-row">
              <span className="info-label">{t('barcode.productName')}</span>
              <span className="info-value">{product?.product_name || product?.name || 'N/A'}</span>
            </div>
            <div className="info-row">
              <span className="info-label">SKU:</span>
              <span className="info-value">{product?.sku || 'N/A'}</span>
            </div>
            <div className="info-row">
              <span className="info-label">{t('barcode.productId')}</span>
              <span className="info-value">#{product?.id || 'N/A'}</span>
            </div>
          </div>

          {/* Barcode Display */}
          {product?.barcode && (
            <div className="barcode-display-box">
              <div className="barcode-label">{t('barcode.generated')}</div>
              <div className="barcode-code">
                <code>{product.barcode}</code>
              </div>
            </div>
          )}

          {/* Quick Actions */}
          <div className="actions-grid">
            <button
              type="button"
              onClick={handleCopy}
              disabled={copying}
              className="action-btn copy-btn"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
              </svg>
              <span>{copying ? t('barcode.copied') : t('barcode.copy')}</span>
            </button>

            <button
              type="button"
              onClick={handlePrint}
              disabled={printing}
              className="action-btn print-btn"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/>
                <path d="M6 14h12v8H6z"/>
              </svg>
              <span>{printing ? t('barcode.printing') : t('barcode.printLabel')}</span>
            </button>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="modal-footer">
          <button type="button" onClick={onClose} className="btn-secondary">
            {t('barcode.continueLater')}
          </button>
          <button type="button" onClick={onViewProduct} className="btn-primary">
            {t('barcode.viewProduct')}
          </button>
        </div>
      </div>

      <style>{`
        .barcode-modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.5);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 1000;
          animation: fadeIn 0.2s ease-out;
        }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        .barcode-modal-content {
          background: white;
          border-radius: 12px;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
          max-width: 500px;
          width: 90%;
          max-height: 90vh;
          overflow-y: auto;
          animation: slideUp 0.3s ease-out;
        }

        @keyframes slideUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .modal-header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          padding: 24px;
          border-bottom: 1px solid #e1e4e8;
          background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%);
        }

        .modal-header h2 {
          margin: 0;
          font-size: 18px;
          font-weight: 600;
          color: #24292e;
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .modal-header p {
          margin: 4px 0 0 0;
          font-size: 13px;
          color: #666;
        }

        .modal-close {
          background: none;
          border: none;
          font-size: 24px;
          color: #666;
          cursor: pointer;
          padding: 0;
          width: 32px;
          height: 32px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 6px;
          transition: all 0.15s ease;
        }

        .modal-close:hover {
          background: #f0f0f0;
          color: #24292e;
        }

        .modal-body {
          padding: 24px;
        }

        .product-info {
          background: #f8f9fa;
          border: 1px solid #e1e4e8;
          border-radius: 8px;
          padding: 16px;
          margin-bottom: 20px;
        }

        .info-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 8px 0;
          font-size: 13px;
        }

        .info-row:not(:last-child) {
          border-bottom: 1px solid #d1d5da;
        }

        .info-label {
          font-weight: 500;
          color: #24292e;
        }

        .info-value {
          color: #0366d6;
          font-family: 'SF Mono', 'Monaco', monospace;
          font-weight: 500;
        }

        .barcode-display-box {
          background: #f8f9fa;
          border: 2px solid #28a745;
          border-radius: 8px;
          padding: 20px;
          margin-bottom: 20px;
          text-align: center;
        }

        .barcode-label {
          font-size: 12px;
          font-weight: 600;
          color: #28a745;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 12px;
        }

        .barcode-code code {
          font-family: 'SF Mono', 'Monaco', 'Cascadia Code', monospace;
          font-size: 24px;
          font-weight: 600;
          color: #0366d6;
          letter-spacing: 2px;
          background: white;
          padding: 12px 16px;
          border-radius: 6px;
          border: 1px solid #d1d5da;
          display: inline-block;
        }

        .actions-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 12px;
          margin-bottom: 20px;
        }

        .action-btn {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          padding: 12px 16px;
          border: 1px solid #d1d5da;
          border-radius: 6px;
          background: white;
          font-size: 13px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.15s ease;
        }

        .action-btn:hover:not(:disabled) {
          background: #f6f8fa;
          border-color: #0366d6;
          color: #0366d6;
        }

        .action-btn:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .action-btn svg {
          width: 18px;
          height: 18px;
        }

        .modal-footer {
          display: flex;
          gap: 12px;
          padding: 16px 24px;
          border-top: 1px solid #e1e4e8;
          background: #f8f9fa;
          border-radius: 0 0 12px 12px;
        }

        .btn-secondary,
        .btn-primary {
          flex: 1;
          padding: 10px 16px;
          border: none;
          border-radius: 6px;
          font-size: 13px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.15s ease;
        }

        .btn-secondary {
          background: white;
          color: #24292e;
          border: 1px solid #d1d5da;
        }

        .btn-secondary:hover {
          background: #f6f8fa;
          border-color: #0366d6;
        }

        .btn-primary {
          background: #0366d6;
          color: white;
        }

        .btn-primary:hover {
          background: #0256c7;
        }

        @media (max-width: 600px) {
          .barcode-modal-content {
            width: 95%;
            max-height: 95vh;
          }

          .modal-header {
            padding: 16px;
          }

          .modal-body {
            padding: 16px;
          }

          .modal-footer {
            padding: 12px 16px;
            flex-direction: column;
          }

          .actions-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  );
};

export default PostCreationBarcodeModal;
